/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/
-- Find total customers by countries
SELECT
	country, 
	COUNT(customer_key) as total_customers
FROM	gold.dim_customers 
GROUP BY	country
ORDER BY 2 desc
-- Find total customers by gender
SELECT
	gender, 
	COUNT(customer_key) as total_customers
FROM	gold.dim_customers 
GROUP BY	gender
ORDER BY 2 desc
-- Find total products by category
SELECT
	category, 
	COUNT(product_key) as total_products
FROM	gold.dim_products 
GROUP BY	category
ORDER BY 2 desc
-- What is the average cost in each category?
SELECT
	category, 
	AVG(cost) as avg_price
FROM	gold.dim_products
GROUP BY	category
ORDER BY 2 desc
-- What is the total revenue generated by each category?
SELECT
	dp.category, 
	SUM(fs.sales_amount) as total_revenue
FROM		gold.fact_sales fs	
LEFT JOIN	gold.dim_products dp
	ON	fs.product_key = dp.product_key
GROUP BY	dp.category
ORDER BY 2 desc
-- Find total revenue generated by each customer
SELECT
	dc.customer_key, 
	dc.first_name,
	dc.last_name,
	SUM(fs.sales_amount) as total_revenue
FROM	gold.fact_sales fs	
JOIN	gold.dim_customers dc
	ON	fs.customer_key = dc.customer_key
GROUP BY	dc.customer_key,dc.first_name,dc.last_name
ORDER BY total_revenue desc
-- What is the distribution of sold items across countries?
SELECT
	dc.country, 
	SUM(quantity) as total_sold_items
FROM		gold.fact_sales fs
LEFT JOIN	gold.dim_customers dc
	ON	fs.customer_key = dc.customer_key 
GROUP BY	dc.country
ORDER BY total_sold_items desc